-- V39: checkpoint semantico sin transformacion de datos.
--
-- actividad_recurso nace vacia en V36 y su columna cantidad ya representa las
-- unidades TOTALES del recurso consumidas por una reserva. No existe una columna
-- cantidad_por_participante ni filas con la semantica anterior que convertir.
-- participantes_por_reserva es independiente y no multiplica esta cantidad.
