"""Operational state is intentionally independent from phase kind."""

from enum import StrEnum


class OperationalState(StrEnum):
    PENDING = "PENDING"
    RUNNING = "RUNNING"
    WAITING_FOR_QUOTA = "WAITING_FOR_QUOTA"
    WAITING_FOR_NETWORK = "WAITING_FOR_NETWORK"
    RECOVERING = "RECOVERING"
    REVIEWING = "REVIEWING"
    CORRECTING = "CORRECTING"
    PAUSED = "PAUSED"
    BLOCKED = "BLOCKED"
    HUMAN_DECISION_REQUIRED = "HUMAN_DECISION_REQUIRED"
    FAILED_SAFE = "FAILED_SAFE"
    COMPLETED = "COMPLETED"


class WorkPhaseKind(StrEnum):
    IMPLEMENTATION = "IMPLEMENTATION"
    AUDIT = "AUDIT"
    CORRECTION = "CORRECTION"
    DOCUMENTATION = "DOCUMENTATION"
    VALIDATION = "VALIDATION"
    PUBLICATION = "PUBLICATION"
